---
name: CI-python

on:
  push:
    branches: ["development"] #["main", "development"]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ["3.7", "3.8", "3.9"]

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e git+https://github.com/martinschatz-cz/SciAugment.git@development#egg=SciAugment

      - name: Run tests
        run: |
          pytest tests/
---
